In [49]:
import random

In [50]:
import numpy as np

In [71]:
# Task 1
a = np.random.randint(10, size=10)
b = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
a

array([2, 8, 5, 6, 8, 9, 6, 1, 6, 7])

In [73]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
# Task 2
matrix_1 = np.array([[0] * 3] * 3)

In [54]:
matrix_1

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [66]:
# Task 3
matrix_2 = np.random.randint(1, 10, size=(5, 5))

In [67]:
matrix_2

array([[7, 5, 6, 8, 1],
       [2, 7, 8, 4, 4],
       [3, 5, 6, 9, 9],
       [9, 8, 1, 2, 1],
       [5, 3, 8, 9, 6]])

In [64]:
# Task 4
matrix_3 = np.random.rand(4, 4)

In [65]:
matrix_3

array([[0.67405889, 0.90936621, 0.40629583, 0.91703797],
       [0.65482098, 0.88032633, 0.95114619, 0.63703258],
       [0.32417158, 0.28811092, 0.08304635, 0.21398965],
       [0.42913324, 0.4005845 , 0.67657058, 0.10650645]])

In [75]:
# Task 5
u = np.random.randint(10, size=5)
j = np.random.randint(10, size=5)

In [103]:
u

array([1, 4, 2, 3, 4])

In [104]:
j

array([0, 9, 9, 4, 4])

In [105]:
res_1 = u + j
res_2 = u - j
res_3 = u * j

In [106]:
res_1

array([ 1, 13, 11,  7,  8])

In [107]:
res_2

array([ 1, -5, -7, -1,  0])

In [108]:
res_3

array([ 0, 36, 18, 12, 16])

In [100]:
# Task 6
w = np.random.randint(10, size=7)
e = np.random.randint(10, size=7)

res_7 = np.dot(w, e)

In [85]:

res_7

150

In [90]:
# Task 7
matrix_4 = np.random.randint(1, 10, size=(2, 2)).reshape(4, 1)
matrix_5 = np.random.randint(1, 10, size=(3, 3)).reshape(1, 9)
res_8 = np.dot(matrix_4, matrix_5)

In [91]:
res_8

array([[ 4,  8,  4,  8, 10, 16,  6,  4, 18],
       [16, 32, 16, 32, 40, 64, 24, 16, 72],
       [ 6, 12,  6, 12, 15, 24,  9,  6, 27],
       [10, 20, 10, 20, 25, 40, 15, 10, 45]])

In [88]:
# Task 8
matrix_6 = np.random.randint(1, 10, size=(3, 3))
matrix_6_inv = np.linalg.inv(matrix_6)

In [89]:
matrix_6_inv

array([[ 0.26693227, -0.0438247 , -0.02788845],
       [ 0.10358566, -0.09163347,  0.12350598],
       [-0.21912351,  0.15537849,  0.00796813]])

In [92]:
# Task 9
matrix_7_T = np.random.rand(4, 4).T

In [93]:
matrix_7_T

array([[0.42897477, 0.14339276, 0.98120783, 0.82601768],
       [0.32280887, 0.00101107, 0.18341815, 0.18796541],
       [0.88017461, 0.19163807, 0.55552504, 0.88486517],
       [0.73669366, 0.12092143, 0.42594294, 0.01426258]])

In [94]:
# Task 10
matrix_8 = np.random.randint(1, 10, size=(3, 4))
r = np.random.randint(10, size=4)
res_9 = matrix_8.dot(r)

In [95]:
res_9

array([31, 53, 18])

In [96]:
# Task 11
matrix_9 = np.random.rand(2, 3)
t = np.random.rand(3)
res_10 = matrix_9.dot(t)

In [97]:
res_10

array([0.28552111, 0.58852302])

In [113]:
# Task 12 
matrix_10 = np.random.randint(1, 10, size=(2, 2))
matrix_11 = np.random.randint(1, 10, size=(2, 2))
res_11 = np.multiply(matrix_10, matrix_11)

In [114]:
res_11

array([[40,  9],
       [42, 42]])

In [115]:
# Task 13
matrix_12 = np.random.randint(1, 10, size=(2, 2))
matrix_13 = np.random.randint(1, 10, size=(2, 2))
res_12 = np.dot(matrix_10, matrix_11)

In [116]:
res_12

array([[61, 45],
       [72, 60]])

In [117]:
# Task 14
matrix_14 = np.random.randint(1, 100, size=(5, 5))
res_13 = np.sum(matrix_14)

In [118]:
res_13

1384

In [121]:
# Task 15
matrix_15 = np.random.randint(1, 10, size=(4, 4))
res_14 = matrix_15.max() - matrix_15.min()

In [122]:
res_14

8

In [123]:
# Task 16 
matrix_16 = np.random.rand(3, 3)
res_15 = np.sum(matrix_16, axis=1)

In [124]:
res_15

array([2.33208404, 1.07311334, 1.89267545])

In [125]:
# Task 17
matrix_16 = np.random.randint(1, 10, size=(3, 4))**2

In [126]:
matrix_16

array([[36, 81, 36, 25],
       [49, 64,  4, 36],
       [ 1, 16,  4, 64]])

In [ ]:
# Task 18
